localization_test_node:
  ros__parameters:
    vocab_path: "~/Documents/ORB_SLAM3/Vocabulary/ORBvoc.txt"
    config_path: "~/Documents/ORB_SLAM3_Relocalization/src/orb_slam3_relocalization/config/tum_fr3.yaml"
    video_path: "~/Documents/ORB_SLAM3_Relocalization/data/rgbd_dataset_freiburg3_long_office_household_validation/rgbd_dataset_freiburg3_long_office_household_validation_rgb.mp4"
    output_csv: "~/Documents/ORB_SLAM3_Relocalization/localization_test_log.csv"
    mode: "video"
