camera_node:
  ros__parameters:
    video_path: "~/Documents/ORB_SLAM3_Relocalization/data/rgbd_dataset_freiburg3_long_office_household_validation/rgbd_dataset_freiburg3_long_office_household_validation_rgb.mp4"
    # video_path: "~/Documents/ORB_SLAM3_Relocalization/data/rgbd_dataset_freiburg3_long_office_household/rgbd_dataset_freiburg3_long_office_household_rgb.mp4"
    # video_path: "~/Documents/ORB_SLAM3_Relocalization/data/dataset1.mp4"
    camera_id: 0 # used when video_path is empty (webcam mode)
    timestamp_start: 1341848149.1989 # first timestamp from validation groundtruth.txt (0.0 = ROS wall clock)
    # timestamp_start: 1341847980.7900 # for tum_fr3_long_office_household, first timestamp from groundtruth.txt

relocalization_node:
  ros__parameters:
    vocab_path: "~/Documents/ORB_SLAM3/Vocabulary/ORBvoc.txt"
    config_path: "~/Documents/ORB_SLAM3_Relocalization/src/orb_slam3_relocalization/config/tum_fr3.yaml"
    # config_path: "~/Documents/ORB_SLAM3_Relocalization/src/orb_slam3_relocalization/config/webcam_complete.yaml"
    visualize: true
    use_weighted_pnp: true # true = weighted PnP (landmark-aware), false = OpenCV solvePnPRansac
    landmark_weight: 1.0
    background_weight: 0.0
