%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 535.4
Camera1.fy: 539.2
Camera1.cx: 320.1
Camera1.cy: 247.6

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0 

Camera.fps: 30
Camera.RGB: 1
Camera.width: 640
Camera.height: 480

ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# For ROS program
System.SaveAtlasToFile: "./maps/fr3_household_map_2"
# Comment the line below if you want to build the new atlas from the map created by the SLAM system. If you uncomment it, the atlas will be loaded from the file specified in the line below.
System.LoadAtlasFromFile: "./maps/fr3_household_map"

# For withour ROS program
# System.SaveAtlasToFile: "../../ORB_SLAM3_Relocalization/maps/map3"
# System.LoadAtlasFromFile: "../../ORB_SLAM3_Relocalization/maps/map"

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

Relocalization.BowSimilarityThreshold: 0.018
Relocalization.MinInliers: 15
Relocalization.HammingThreshold: 80

# Visualization settings
Visualization.ProcessWidth: 640
Visualization.ProcessHeight: 480
Visualization.DisplayWidth: 640
Visualization.DisplayHeight: 480

Map.ZoomScale: 2.5
Map.OffsetX: -100
Map.OffsetY: 200

# Map.ZoomScale: 10
# Map.OffsetX: 300
# Map.OffsetY: 500